### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Vansh-Sharma-Git** [sauravhathi/Hitbullseye-Automate-Tool#13]
![Screenshot 2024-01-07 142904](https://github.com/sauravhathi/Hitbullseye-Automate-Tool/assets/110225237/9491ebb4-4959-4c99-857c-79f76cd31b69)
![image](https://github.com/sauravhathi/Hitbullseye-Automate-Tool/assets/110225237/5d3bc229-aead-43a4-a5e8-5bce15609ed9)

**Comment by sauravhathi** [comment]
This bug has been `fixed`. **Please update the extension by `downloading `the latest**
